samples.json

Updating links and text for Angular sample code.

fix pointers to angular sample

---

Basic/Python/QiPy/Python3/SdsClient.py

 Provide a string to json.loads() for pre-3.6 Python compatibility

---

.gitignore
Basic/Java/src/samples/SdsClient.java
Basic/Java/src/samples/SdsDatagroup.java
Basic/Java/src/samples/SdsDatagroups.java
Basic/Java/src/samples/SdsDataview.java
Basic/Java/src/samples/SdsDataviewIndexConfig.java
Basic/Java/src/samples/SdsDataviewMapping.java
Basic/Java/src/samples/SdsDataviewMappingColumn.java
Basic/Java/src/samples/SdsDataviewMappingRule.java
Basic/Java/src/samples/SdsDataviewQuery.java
Basic/Java/src/samples/SdsDataviewQueryQuery.java

This update adds dataviews to the Java code.  No example is given because the example doesn't have a type that is usable in the dataviews

Updating Java to include Dataviews

---

basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibraries/Program.cs
basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibraries/SdsClientLibrariesCore.csproj
basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibraries/appsettings.json
basic_samples/SDS/DotNet/SdsRestApiCore/Program.cs
basic_samples/SDS/DotNet/SdsRestApiCore/SdsRestApiCore.csproj
basic_samples/SDS/DotNet/SdsRestApiCore/SdsSecurityHandler.cs
basic_samples/SDS/DotNet/SdsRestApiCore/appsettings.json

Update the basic samples to use AuthenticationHandler and IdentityModel.

Authentication update

---

basic_samples/SDS/JavaScript/NodeJs/Sample.js
basic_samples/SDS/JavaScript/NodeJs/SdsClient.js
basic_samples/SDS/JavaScript/NodeJs/config.js
basic_samples/SDS/JavaScript/NodeJs/readme.rst

introduced api versioning into NodeJS sample

Api versioning nodejs

---

basic_samples/SDS/JavaScript/Angular/readme.rst
basic_samples/SDS/JavaScript/Angular/src/app/app.component.ts
basic_samples/SDS/JavaScript/Angular/src/app/osiconfiguration.service.ts
basic_samples/SDS/JavaScript/Angular/src/app/sds.rest.service.ts

added api versioning to angular sample

add api versioning to angular sample

---

advanced_samples/PerfmonSample/Python3/config.ini
advanced_samples/PerfmonSample/Python3/program.py
advanced_samples/PerfmonSample/Python3/sds_client.py
basic_samples/SDS/Python/SDSPy/Python2/SdsClient.py
basic_samples/SDS/Python/SDSPy/Python2/config.ini
basic_samples/SDS/Python/SDSPy/Python2/program.py
basic_samples/SDS/Python/SDSPy/Python2/readme.rst
basic_samples/SDS/Python/SDSPy/Python2/requirements.txt
basic_samples/SDS/Python/SDSPy/Python3/SdsClient.py
basic_samples/SDS/Python/SDSPy/Python3/config.ini
basic_samples/SDS/Python/SDSPy/Python3/program.py
basic_samples/SDS/Python/SDSPy/Python3/readme.rst
basic_samples/SDS/Python/SDSPy/Python3/requirements.txt
basic_samples/SDS/Python/SDSPy/readme.rst

modified readme and requirements too

Updating python examples

---

advanced_samples/PerfmonSample/Python3/config.ini
advanced_samples/PerfmonSample/Python3/program.py
advanced_samples/PerfmonSample/Python3/sds_client.py
basic_samples/SDS/Python/SDSPy/Python2/SdsClient.py
basic_samples/SDS/Python/SDSPy/Python2/config.ini
basic_samples/SDS/Python/SDSPy/Python2/program.py
basic_samples/SDS/Python/SDSPy/Python3/SdsClient.py
basic_samples/SDS/Python/SDSPy/Python3/config.ini
basic_samples/SDS/Python/SDSPy/Python3/program.py

Update python examples to use the identity server based authentication.

Identity update

---

advanced_samples/PIToOcsOmfSample/Dotnet/readme.rst
advanced_samples/PItoOCSviaAPISample/DotNet/readme.rst
advanced_samples/PerfmonSample/Python3/sds_client.py
advanced_samples/PerfmonSample/Python3/sds_stream.py
basic_samples/IngressClientLibraries/DotNet/readme.rst
basic_samples/SDS/DotNet/DotnetLinuxQuickstart.rst
basic_samples/SDS/DotNet/README.rst
basic_samples/SDS/DotNet/SdsRestApiCore/Program.cs
basic_samples/SDS/DotNet/readme_REST.rst
basic_samples/SDS/DotNet/readme_SdsLibs.rst
basic_samples/SDS/Java/readme.rst
basic_samples/SDS/Java/src/samples/SdsClient.java
basic_samples/SDS/Java/src/samples/SdsStream.java
basic_samples/SDS/JavaScript/Angular/readme.rst
basic_samples/SDS/JavaScript/Angular/src/app/datasrc/datasrc.component.html
basic_samples/SDS/JavaScript/NodeJs/readme.rst
basic_samples/SDS/Python/SDSPy/Python2/SdsClient.py
basic_samples/SDS/Python/SDSPy/Python2/program.py
basic_samples/SDS/Python/SDSPy/Python2/readme.rst
basic_samples/SDS/Python/SDSPy/Python3/SdsClient.py
basic_samples/SDS/Python/SDSPy/Python3/program.py
basic_samples/SDS/Python/SDSPy/Python3/readme.rst
basic_samples/SDS/Python/SDSPy/readme.rst
basic_samples/SDS/README.rst

SdsView was renamed to SdsStreamView. Updated this doc to reflect this.

Updated all readme files with names and links

---

advanced_samples/PerfmonSample/Python3/program.py
advanced_samples/PerfmonSample/Python3/sds_client.py
basic_samples/SDS/DotNet/SdsRestApiCore/Program.cs
basic_samples/SDS/Java/src/samples/Program.java
basic_samples/SDS/JavaScript/Angular/src/app/datasrc/datasrc.component.ts
basic_samples/SDS/JavaScript/Angular/src/app/sds.rest.service.ts
basic_samples/SDS/Python/SDSPy/Python3/SdsClient.py
basic_samples/SDS/Python/SDSPy/Python3/program.py

switched back GetLastValue to single object instead of collection
added verbless routes to Angular sample

added verbless routes to Angular sample

---

basic_samples/SDS/JavaScript/NodeJs/Sample.js
basic_samples/SDS/JavaScript/NodeJs/SdsClient.js
basic_samples/SDS/Python/SDSPy/Python2/SdsClient.py
basic_samples/SDS/Python/SDSPy/Python2/WaveData.py
basic_samples/SDS/Python/SDSPy/Python2/program.py
basic_samples/SDS/Python/SDSPy/Python3/program.py

fixed WaveData in Py2 that was not returning values
updated to verbless routes 
fixed few typos

Verbless routes for Node and Python2

---

basic_samples/Identity/DotNet/HybridFlow/HybridFlow.cs
basic_samples/Identity/DotNet/HybridFlow/Program.cs
basic_samples/Identity/DotNet/HybridFlow/README.md

- Add support for hybrid clients that do not allow offline access
- Update README

Handle HybridClients that do not allow offline_access

---

basic_samples/SDS/Java/sdsjava/pom.xml

removing unneaded dependencies.

Update to sdsjava example

---

azure-pipelines-on-prem.yml
miscellaneous/on_prem_testing.md
ocs_samples/basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibraries/readme.md
ocs_samples/basic_samples/SDS/DotNet/SdsRestApiCore/SdsRestApiCore/readme.md
omf_samples/basic_samples/OMF_API/CSharp/OMF_API/OMF_API.csproj
omf_samples/basic_samples/OMF_API/CSharp/OMF_API/Program.cs
omf_samples/basic_samples/OMF_API/CSharp/OMF_API/appsettings.json
omf_samples/basic_samples/OMF_API/CSharp/OMF_API/readme.md
omf_samples/basic_samples/OMF_API/Java/omfapijava/config.properties
omf_samples/basic_samples/OMF_API/Java/omfapijava/readme.md
omf_samples/basic_samples/OMF_API/Java/omfapijava/src/main/java/com/github/osisoft/omfapi/Program.java
omf_samples/basic_samples/OMF_API/Python3/config.ini
omf_samples/basic_samples/OMF_API/Python3/program.py
omf_samples/basic_samples/OMF_API/Python3/readme.md
omf_samples/basic_samples/OMF_API/Readme.md

not fully functional yet due to issues

Adding pipelines for unprem testing 

---

miscellaneous/versionHistory.md
ocs_samples/basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibraries/SdsClientLibrariesCore.csproj
ocs_samples/basic_samples/SDS/Python/SDSPy/Python3/program.py
ocs_samples/basic_samples/SDS/Python/SDSPy/Python3/requirements.txt
ocs_samples/library_samples/Python3/ocs_sample_library_preview/Streams.py
ocs_samples/library_samples/Python3/setup.py

fixing an error in streams for a recent pull

Updating versions based on recent pulls

---

ocs_samples/library_samples/Python3/ocs_sample_library_preview/Dataviews.py
ocs_samples/library_samples/Python3/setup.py

Fix my broken PR

---

ocs_samples/basic_samples/Authentication/ClientCredentialFlow/DotNet/ClientCredentialFlow/ClientCredentialFlow.csproj
ocs_samples/basic_samples/Authentication/ClientCredentialFlow/DotNet/ClientCredentialFlow/Program.cs
ocs_samples/basic_samples/Authentication/ClientCredentialFlow/DotNet/ClientCredentialFlow/README.md
ocs_samples/basic_samples/Authentication/ClientCredentialFlow/DotNet/ClientCredentialFlow/appsettings.json
ocs_samples/basic_samples/Authentication/HybridFlow/DotNet/HybridFlow/HybridFlow.cs
ocs_samples/basic_samples/Authentication/HybridFlow/DotNet/HybridFlow/HybridFlow.csproj
ocs_samples/basic_samples/Authentication/HybridFlow/DotNet/HybridFlow/Program.cs
ocs_samples/basic_samples/Authentication/HybridFlow/DotNet/HybridFlow/README.md
ocs_samples/basic_samples/Authentication/HybridFlow/DotNet/HybridFlow/SystemBrowser.cs
ocs_samples/basic_samples/Authentication/HybridFlow/DotNet/HybridFlow/appsettings.json
ocs_samples/basic_samples/Authentication/ImplicitFlow/DotNet/ImplicitFlow/README.md
ocs_samples/basic_samples/Authentication/ImplicitFlow/DotNet/ImplicitFlow/wwwroot/app.js
ocs_samples/basic_samples/Authentication/ImplicitFlow/DotNet/ImplicitFlow/wwwroot/config.js
ocs_samples/basic_samples/Authentication/ImplicitFlow/DotNet/ImplicitFlow/wwwroot/index.html

- Update packages
- Update version

Update packages and version

---

ocs_samples/basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibraries/appsettings.json
ocs_samples/basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibraries/readme.md
ocs_samples/basic_samples/SDS/DotNet/SdsRestApiCore/SdsRestApiCore/appsettings.json
ocs_samples/basic_samples/SDS/DotNet/SdsRestApiCore/SdsRestApiCore/readme.md
ocs_samples/basic_samples/SDS/Java/sdsjava/config.properties
ocs_samples/basic_samples/SDS/Java/sdsjava/readme.md
ocs_samples/basic_samples/SDS/JavaScript/Angular/readme.md
ocs_samples/basic_samples/SDS/JavaScript/Angular/src/app/config/oidc.config.json
ocs_samples/basic_samples/SDS/JavaScript/Angular/src/app/config/sdsconfig.json
ocs_samples/basic_samples/SDS/JavaScript/NodeJs/config.js
ocs_samples/basic_samples/SDS/JavaScript/NodeJs/readme.md
ocs_samples/basic_samples/SDS/Python/SDSPy/Python3/config.ini
ocs_samples/basic_samples/SDS/Python/SDSPy/Python3/readme.md

Placeholders had different text across different samples
Changed them so they all match

changed placeholders to match across samples

---

ocs_samples/basic_samples/Authentication/ImplicitFlow/DotNet/ImplicitFlow/README.md
ocs_samples/basic_samples/SDS/JavaScript/Angular/readme.md
ocs_samples/basic_samples/SDS/JavaScript/NodeJs/Sample.js
ocs_samples/basic_samples/SDS/JavaScript/NodeJs/readme.md
piwebapi_samples/Angular/AngularPIWebAPISample/README.md
piwebapi_samples/AngularJS/README.md

And not to use HTTP beyond simple testing

Updating to list ports and make clear it is HTTP

---

piwebapi_samples/Angular/AngularPIWebAPISample/README.md
piwebapi_samples/AngularJS/README.md
piwebapi_samples/JQuery/README.md
piwebapi_samples/Python/README.md
piwebapi_samples/R/README.md
piwebapi_samples/README.md

Updating some readme docs with some suggestions from the Web API team.

update readme docs

---

ocs_samples/library_samples/Python3/ocs_sample_library_preview/BaseClient.py
ocs_samples/library_samples/Python3/ocs_sample_library_preview/OCSClient.py
ocs_samples/library_samples/Python3/setup.py

 Request timeout header

---

piwebapi_samples/Python/azure-pipelines.yml
piwebapi_samples/Python/run_all_tests.py
piwebapi_samples/Python/test_write_attributes.py
piwebapi_samples/R/azure-pipelines.yml
piwebapi_samples/R/run_tests.R
piwebapi_samples/R/sampleCode.R

Hi Derek,
Please, let me know if something is missing or wrong...
Thanks,
Dmitriy

Changing R and Python tests to produce JUnit output results

---

samples.json

In regards to this WI: https://dev.azure.com/osieng/engineering/_workitems/edit/130989

Updated the out of date Java, NodeJs, and Python github links

---

CODEOWNERS

changed the code owners to the new product readiness guild github team

changed code owners to readiness team

---

miscellaneous/build_templates/analysis.yml
miscellaneous/build_templates/config.yml
miscellaneous/build_templates/variables.yml

Created a merged version of each of the following files:
- Analysis.yml
- Config.yml
- Variables.yml
These will be referenced by the azure-pipline.yml files in each of the sample repositories to improve maintainability

Miscellaneous folder update

---

miscellaneous/build_templates/analysis.yml
miscellaneous/build_templates/code-analysis.yml

Reverts osisoft/OSI-Samples#233
Reverting to move changes to a new file, code-analysis.yml

Revert "Analysis update"

---

miscellaneous/build_templates/code-analysis.yml

This PR adds to Force flag to overwrite any current file that might not have been cleaned up from a previous run
Passed build: https://dev.azure.com/osieng/engineering/_build/results?buildId=554120&view=results
From MS docs.

Force new file creation in case of artifacting

---

miscellaneous/build_templates/code-analysis.yml

This uses the newer task that doesn't need tokens. Passed build here https://dev.azure.com/osieng/engineering/_build/results?buildId=550969&view=results

Use SynopsysPolaris@1 Task

---

README.md
docs/Cloud_Operations.md
miscellaneous/all_status_badges.md

Renamed AVEVA Data Hub to CONNECT data services.
Renamed ADH to CDS.
Updated OCS links to Aveva Links

Renamed AVEVA Data Hub to CONNECT data services.

---

miscellaneous/build_templates/code-analysis.yml

Polaris ADO Extension Migration:
Updated blackduck task

Polaris ADO Extension Migration
